// Auto-generated API method registration
// Generated by Askama template engine
(function() {
    if (!window.auroraview || !window.auroraview._registerApiMethods) {
        console.error('[AuroraView] Event bridge not initialized!');
        return;
    }
{% for entry in api_methods %}
{% if !entry.methods.is_empty() %}
    window.auroraview._registerApiMethods('{{ entry.namespace }}', [{% for m in entry.methods %}'{{ m }}'{% if !loop.last %}, {% endif %}{% endfor %}]);
{% endif %}
{% endfor %}
})();

