/**
 * Emit event to JavaScript using window.auroraview.trigger()
 * 
 * This template is used by Rust to dispatch events from Python to JavaScript.
 * Generated by Askama template engine.
 */
(function() {
    if (window.auroraview && window.auroraview.trigger) {
        window.auroraview.trigger('{{ event_name }}', JSON.parse('{{ event_data }}'));
    } else {
        console.error('[AuroraView] Event bridge not ready, cannot emit event: {{ event_name }}');
    }
})();

