/**
 * Load URL by setting window.location.href
 * 
 * This template is used by Rust to navigate the WebView to a new URL.
 * Generated by Askama template engine.
 */
window.location.href = '{{ url }}';

