name: CI

# This workflow runs comprehensive testing on main branch and when explicitly requested.
# For PR checks, see pr-checks.yml which runs essential validations.

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]  # Only run on labeled PRs (e.g., 'full-ci', 'test-wheels')
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  # Quick validation - runs on every PR, depends on version check
  quick-test:
    name: Quick Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Allow other Python versions to continue if one fails
      matrix:
        python-version: ["3.8", "3.10", "3.12"]  # Test min, stable, and recent stable

    steps:
      - uses: actions/checkout@v5

      - name: Setup AuroraView Environment
        uses: ./.github/actions/setup-auroraview
        with:
          python-version: ${{ matrix.python-version }}
          rust-components: 'clippy'
          cache-key-suffix: 'quick-test'

      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with:
          test-type: 'basic'
          generate-stubs: 'true'

  # Code quality and linting - runs on every PR
  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup AuroraView Environment
        uses: ./.github/actions/setup-auroraview
        with:
          python-version: "3.10"
          rust-components: 'rustfmt,clippy'
          cache-key-suffix: 'lint'

      - name: Run linting and formatting checks
        run: just ci-lint

  # Comprehensive testing - runs on main branch and when requested
  full-test:
    name: Full Test Suite (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'full-ci') || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.10", "3.12"]
        include:
          # Test additional Python versions on Ubuntu only
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v5

      - name: Setup AuroraView Environment
        uses: ./.github/actions/setup-auroraview
        with:
          python-version: ${{ matrix.python-version }}
          cache-key-suffix: 'full-test-${{ matrix.os }}'

      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with:
          test-type: 'full'
          upload-artifacts: 'true'
          artifact-name: 'full-test-results-${{ matrix.os }}-py${{ matrix.python-version }}'

  # Wheel testing - only for critical combinations
  wheel-test:
    name: Wheel Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'test-wheels')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.10"]  # Test min and stable versions

    steps:
      - uses: actions/checkout@v5

      - name: Build and Test Wheel
        uses: ./.github/actions/build-wheel
        with:
          python-version: ${{ matrix.python-version }}
          test-wheel: 'true'
          upload-wheel: 'true'
          artifact-name: 'test-wheels'

  # Documentation tests - lightweight
  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-docs-
            ${{ runner.os }}-cargo-

      - name: Run doc tests
        run: cargo test --doc

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items

  # Overall CI status check - this job will be required for PR merging
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [quick-test, lint]
    if: always()

    steps:
      - name: Check all required jobs
        run: |
          # Check if all required jobs passed
          if [[ "${{ needs.quick-test.result }}" != "success" ]]; then
            echo "❌ Quick tests failed"
            exit 1
          fi
          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            echo "❌ Linting failed"
            exit 1
          fi
          echo "✅ All required CI checks passed"

